### ISSUE TITLE
Stats mapping issue

### ISSUE THREAD

**Issue by yinxu1000** [dpdkcap/dpdkcap#8] opened 2016-10-25 02:37 UTC
Hi，

I met a problem using dpdkcap, can you help me ? The error I met was as follow.  My operating system is ubuntu 12.04, the version of dpdk is 16.07, and ethernet controller is Intel Corporation I350 Gigabit Network Connection.

I found  **rte_eth_dev_set_rx_queue_stats_mapping (port, q, q)**  in **port_init** function  return -95, which was caused by **struct rte_eth_dev** did not support **queue_stats_mapping_set** function.

EAL: Detected 64 lcore(s)
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:16:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:16:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:16:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:16:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:46:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:46:00.1 on NUMA socket 1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:46:00.2 on NUMA socket 1
EAL:   probe driver: 8086:1521 rte_igb_pmd
EAL: PCI device 0000:46:00.3 on NUMA socket 1
EAL:   probe driver: 8086:1521 rte_igb_pmd
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 8 allocated
EAL: Error - exiting with code: 1
  Cause: Cannot init port 1
DPDKCAP: Core 1 is writing using file template: /home/rx_%COREID.pcap.lzo.

Best regards,
Xu

**Comment by groud** [comment] 2016-10-25 11:15
Hello,

You should have a look to the issue #2 , where we temporarily resolved the problem.

This seems a recurrent problem, so DPDKCap should be able to handle the error. I however do not have the time now to cleanly fix the problem right now... (see issue #4)

**Comment by yinxu1000** [comment] 2016-10-25 14:19
Thank you for your help. I will read #2 carefully. I found queue_stats_mapping_set function was supported by ixgb driver, and Intel I350 was not ixgb. Then, I commented that line (rte_eth_dev_set_rx_queue_stats_mapping) in port_init, and it worked. Another question: can i get the pcap file without compressed?

**Comment by groud** [comment] 2016-10-25 14:25
Unfortunately, no, this is not implemented yet.
However, this is a good idea and does not seem very complicated to implement. I will open an issue for this feature.

**Comment by yinxu1000** [comment] 2016-10-26 01:51
Thank you very much. Looking forward to that feature.

**Comment by kaijunzhan** [comment] 2017-01-17 17:16
I am also interested in uncompressed format - any hint where to start - replace the whole core_write with pcap write?

**Comment by groud** [comment] 2017-01-17 17:32
Well, a better solution would include the following modifications:
- Add a "no-compression" option handled by the _arpg_ based parser,
- Add the corresponding option into the _core_write.h_ file,
- Modify the whole strategy used into the _core_write.c_ file.

I will have a look to the code to find such a solution, then let you know. :)

**Comment by kaijunzhan** [comment] 2017-01-17 17:57
thank you - it will be also interesting if write can be a socket - or forwarding to another interface instead of writing a pcap file?


________________________________

**Comment by groud** [comment] 2017-01-18 14:00
Ok the job is done. Checkout the develop branch and tell me if it works.

I do not get your point regarding socket forwarding. DPDKCap is a capture tool, it is meant to create capture files...

**Comment by kaijunzhan** [comment] 2017-01-18 16:39
thanks - got the dev code and build ok. Option --no-compression is  now accepted.

the problem is now back to the original one "Cause: cannot init port 0" - in the production code I commented off the line based on your note so I commented off this dev code as well (but I see it no longer return so I guess you try to fix it) but still get the same error

DPDKCAP: rte_eth_rx_queue_setup(...) returned with error code -12
EAL: Error - exiting with code: 1
  Cause: Cannot init port 0



________________________________

**Comment by groud** [comment] 2017-01-18 16:54
Well the problem here is different.
I now added a test so that if the ` rte_eth_dev_set_rx_queue_stats_mapping` function does not work it just displays a warning instead (an obviously display unreliable statistics).

The new error seems to be a out of memory error:
-ENOMEM (-12): Unable to allocate the receive ring descriptors or to allocate network memory buffers from the memory pool when initializing receive descriptors. 

This might come from a too high RX_RING_SIZE requested. Have a look to the #define at the beginning of the _dpdkcap.c_ file, and try to reduce the RX_RING_SIZE, TX_RING_SIZE and NUM_MBUFS values.

**Comment by kaijunzhan** [comment] 2017-01-19 00:04
yes it works by changing the NUM_MBUFS



________________________________

**Comment by groud** [comment] 2017-01-19 07:38
Awesome, I will add an option to change those values without recompiling.
I close this issue. :)

**Closed as completed by groud** 2017-01-19 07:38 UTC

**Comment by kaijunzhan** [comment] 2017-01-20 16:37
sorry did not answer your other question - I was asking if the "writing to" can be network socket based


________________________________

**Comment by groud** [comment] 2017-01-21 12:50
Ok, that is what I understood. :)
But I still do not get in what situation this would be interesting. DPDKCap is meant to capture high speed traffic. So if you need to export the traces through the network this would need even more traffic bandwidth.

Anyway, is think such behaviour might be possible using other linux tools. (like exporting in a fake file, which is linked to a socket). But as I don't see any real application of such behaviour, I belive it is not a priority to implement it. :)
