### ISSUE TITLE
 error: expected ‘;’ before ‘val’

### ISSUE THREAD

**Issue by aghasi** [dpdkcap/dpdkcap#32] opened 2017-07-29 10:50 UTC
I'm using DPDK 16.04 and Ubuntu 16.04. Whey i run `make` command, followin error appears:
```
/opt/dpdk-16.04/build/include/rte_pci.h:262:22: error: expected ‘;’ before ‘val’
  (fd) = (typeof (fd))val;                                \
                      ^
```

**Comment by groud** [comment] 2017-07-29 11:39
Can you try with DPDK 16.11 ?

**Comment by aghasi** [comment] 2017-07-29 13:52
I've tried with DPDK 16.07.2 and it was compiled successfully. 
The line 262 in `rte_pci.h` is the same in both 16.04 and 16.07.2 version of DPDK.
Can you present a patch for DPDK 16.04? I'm using a DPDK DAQ of Snort on DPDK 16.04. Maybe this DAQ fails on some situations when using DPDK 16.07.2 or later.

**Comment by groud** [comment] 2017-07-29 13:59
Well the problem is that the code that does not compile is not within DPDKCap, but in DPDK itself.
Maybe you need to update your compiler or something like that.

Do you have more logs than that ?

**Comment by xaki23** [comment] 2023-11-23 23:41
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.

**Closed as not planned by xaki23** 2023-11-23 23:41 UTC
