### ISSUE TITLE
Abnormal when performance test with 6G bandwidth

### ISSUE THREAD

**Issue by JotusKuo** [dpdkcap/dpdkcap#38] opened 2019-03-15 07:43 UTC
Hi,
I met an abnormal presentation when performance test with 6G bandwidth. I use dpdp-stable-16.11.8 and development branch of dpdkcap with "sudo ./build/dpdkcap -c 0xff00ff00 -n 4 -- -c 1 -w 14 -S -o /ssd/rx_%COREID  -m 1048575 -d 4096  --log=./0302.log --no-compression" command line.
At the first 22G of stream, everything is fine. After this point, the usage of all write cpu becomes from 100% to 10% and number of free mbuf drops dramatically from 1048575 to 9848. 
Th /ssd is an nvme ssd disk through pcie slot. The speed tested by hdparm is as follow.
sudo hdparm -t /dev/nvme0n1 
/dev/nvme0n1:
 Timing buffered disk reads: 3148 MB in  3.00 seconds = 1048.92 MB/sec

[6G-dpdkcap-test.zip](https://github.com/dpdkcap/dpdkcap/files/2969915/6G-dpdkcap-test.zip)

Is there any suggestions?

**Comment by JotusKuo** [comment] 2019-03-22 09:04
@groud Could you please check this issue and give some advice? And it will be better if you can fix the bug #31 . Thanks.

**Comment by groud** [comment] 2019-03-22 09:11
If you use no compression, the performances are likely going to be very bad. 
Your bottleneck is likely your hard drives. 

Sadly, I did work on dpdkcap during my PhD, and now I lack time to maintain it. Anyone who wants to contribute is welcome though. :)

**Comment by yangye-huaizhou** [comment] 2019-11-20 03:15
@groud We are using the project to complete a project with various test scenarios. I think I can maintian it with my partner in my lab.

**Comment by xaki23** [comment] 2023-11-24 00:03
closing this for now since there have not been any updates to the issue for a while and the root cause seems to mainly be a performance/tuning problem.

writing a tuning guide would be an interesting mission all of its own, volunteers welcome!

**Closed as not planned by xaki23** 2023-11-24 00:03 UTC
